### ISSUE TITLE
When yanking an entire line, it refuses to paste into the current line

### ISSUE THREAD

**Issue by emmanuelrosa** [steveshogren/10-minute-vim-exercises#5]
The first copy/paste (yank) exercise reads as follows:

> ...Use the yank and motion commands to yank capitalized words from the odd numbered lines, and put them inside the parentheses in the following lines that say “put inside here -> ()”.

Lines 9-10 in _yanking.txt_ are:

```
YANK THIS WHOLE LINE WITH NEW LINE
    put inside here -> ()
```

The problem is, when I yank the entire line including the new line with `y$` and then proceed to paste it with `p` or `P` the text is inserted either above the intended line (in the case of `P`) or below it (when using `p`). I don't see a way to paste it in the current line, between the parenthesis as suggested.

**Comment by steveshogren** [comment]
Thanks emmanuel! I reworded that exercise to make it more clear (and possible to solve) :+1:
