### ISSUE TITLE
undo excercise

### ISSUE THREAD

**Issue by gregorybleiker** [steveshogren/10-minute-vim-exercises#6]
Hi there
Maybe not the exact right place to open this, but couldn't find an other place. 
I am going through the exercises and the "basic editing - undo" one says that if you are in insert mode and move around with the arrow keys, then leave insert mode and do an undo, then all the edited text will be undone since you entered insert mode. This is not the way my vim behaves. It does an undo of each edit between the use of the arrow keys. Is this a vim setting that I have active without knowing?

**Comment by steveshogren** [comment]
Yep, you appear to be right. The default setup for Vim allows for "[special special keys](http://vimdoc.sourceforge.net/htmldoc/insert.html#ins-special-special)" and mine appear to be set to not the default! I will update the book and exercises accordingly. Thanks for the bug report!

**Comment by steveshogren** [comment]
I updated the section on "undo" and changed the exercise to better illustrate the differences. 

Thanks a lot for taking the time to log this! This is what I get for writing it in evil-mode ;)
