### ISSUE TITLE
Remember "a" as "Around"

### ISSUE THREAD

**Issue by greenmang0** [steveshogren/10-minute-vim-exercises#7]
You can remember a as "Around", and i as "Inside".

**Comment by danielrangelmoreira** [comment]
Why not i as insert and a as append?

**Comment by steveshogren** [comment]
Cool thanks for the comments, I'll consider them!

**Comment by greenmang0** [comment]
@danielrangelmoreira 

The author is speaking about `text object manipulation` here. In that context `i` as `inside` and `a` as `around` are more logical IMO. At least that's how I remembered them when I learned and started using them for the first time.

**Comment by danielrangelmoreira** [comment]
Tks

**Comment by steveshogren** [comment]
Updated to "around", thanks!
