### ISSUE TITLE
Corrigenda for book

### ISSUE THREAD

**Issue by gregorybleiker** [steveshogren/10-minute-vim-exercises#9]
Hi Steve 
I am still enjoying your book and have worked it front to back. I have found some minor typos and some additional hints, if you like you can correct them if you haven't all ready.
# Hints/Questions:
- Ctrl+V is usually Ctrl+Q on Windows
- p43. You can remember a as “A”, and i as “Inside"... what is the A part? A like "a" house?
Chinese characters not appearing (in Windows)
```
set encoding=utf8
set guifontwide=NSimSun
```
- p 64. regex patterns ex3. There are no words "tim" or "tam" in the mask_numbers.csv ?
- p 69. excercise advanced search/replace ranges/lines: can search/replace really be used to copy the class body? I used yi{

# Typos/Errors
- p30. Basic Editing - Repeat: Excercise:  ct1 instead of ct1(
- p33. Chapter Basic Editing - Misc, Exercises: Some instead of Sum
- p52. Complex Editing Example: The commands are the same, should probably be :g/horse/p
```
:g/test/t$ copy all lines with test to the end of the
file
:g/horse/t$ print all lines with horse
```
- p60. Advanced Search/Replace: difficult to decider =&gt; decipher
- p78. Schedule Day 2 complex editing region commands =%gt complex editing *range* commands

Two more comments:
The schedule for excercising is way more than 10 minutes for me... maybe you could break it down even more?
The only thing I had to learn seperatly from this book was handling multiple files (with tabe etc.) Maybe you could add some excercises for working with multiple files?

Lastly, I would like to thank you for writing this book. It really got me into vi!

Regards
Greg

**Comment by steveshogren** [comment]
Wow, this is amazing! Thanks so much for all the edits! I'll need to go through them this week and put them into the book.

**Comment by steveshogren** [comment]
I just updated the incorrect spots, thanks again!
